import {useEffect,useRef,useState} from 'react';
import {getVersion} from '@tauri-apps/api/app';
import {check,type Update} from '@tauri-apps/plugin-updater';
import {Button} from './ui/button';
import {Progress} from './ui/progress';
import type {AppLocale} from '../lib/i18n';
export function AppUpdate({locale,busy,onBusy,beforeInstall}:{locale:AppLocale;busy:boolean;onBusy:(value:boolean)=>void;beforeInstall:()=>void}){
 const [version,setVersion]=useState('');const [working,setWorking]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState(false);const [percent,setPercent]=useState(0);const [update,setUpdate]=useState<Update|null>(null);const ref=useRef<Update|null>(null);
 const l=(en:string,es:string,zh:string)=>locale==='es'?es:locale==='zh'?zh:en;
 useEffect(()=>{void getVersion().then(setVersion);return()=>{void ref.current?.close();};},[]);
 async function lookup(){setWorking(true);setError(false);setMessage(l('Checking GitHub…','Consultando GitHub…','正在检查 GitHub…'));try{await ref.current?.close();ref.current=null;setUpdate(null);const next=await check({timeout:30000});ref.current=next;setUpdate(next);setMessage(next?l(`Version ${next.version} available`,`Versión ${next.version} disponible`,`版本 ${next.version} 可用`):l('You are up to date.','Tienes la versión más reciente.','已是最新版本。'));}catch(e){setError(true);setMessage(l('Could not check for updates. Retry. ','No se pudo comprobar la actualización. Reintenta. ','无法检查更新，请重试。 ')+String(e));}finally{setWorking(false);}}
 async function install(){if(!update)return;setWorking(true);onBusy(true);setError(false);setPercent(0);try{beforeInstall();let received=0,total=0;setMessage(l('Downloading update…','Descargando actualización…','正在下载更新…'));await update.downloadAndInstall(event=>{if(event.event==='Started')total=event.data.contentLength??0;if(event.event==='Progress'){received+=event.data.chunkLength;setPercent(total?received/total*100:0);}if(event.event==='Finished'){setPercent(100);setMessage(l('Installing · the app will restart','Instalando · la app se reiniciará','正在安装 · 应用将重启'));}});}catch(e){setError(true);setMessage(String(e));}finally{setWorking(false);onBusy(false);}}
 return <details className="relative text-xs" data-testid="app-update"><summary className="cursor-pointer rounded-md border border-white/15 px-3 py-2">{l('Updates','Actualizaciones','更新')} <span className="text-zinc-400">{version}</span></summary><div className="absolute right-0 top-full z-50 mt-2 w-80 max-w-[90vw] space-y-3 rounded-lg border border-white/20 bg-zinc-950 p-4 shadow-xl"><Button size="sm" variant="secondary" disabled={busy||working} onClick={()=>void lookup()}>{l('Check for updates','Buscar actualizaciones','检查更新')}</Button><p role={error?'alert':'status'} className={`break-words ${error?'text-red-300':'text-zinc-300'}`}>{message}</p>{working&&<Progress value={percent}/>} {update&&<><p className="max-h-36 overflow-auto whitespace-pre-wrap text-zinc-400">{update.body}</p><p>{l('Your current session is saved before restarting.','Tu sesión actual se guarda antes de reiniciar.','重启前将保存当前会话。')}</p><Button size="sm" disabled={busy||working} onClick={()=>void install()}>{l('Download & install','Descargar e instalar','下载并安装')}</Button></>}</div></details>;
}
