const {chromium}=require('playwright'),assert=require('node:assert/strict');
const path=require('node:path');
(async()=>{const browser=await chromium.connectOverCDP('http://127.0.0.1:9224');try{
 const p=browser.contexts()[0].pages().find(p=>p.url().includes('tauri.localhost'));assert(p);
 const invoke=(cmd,args={})=>p.evaluate(({cmd,args})=>window.__TAURI_INTERNALS__.invoke(cmd,args),{cmd,args});
 await invoke('plugin:event|emit',{event:'tauri://drag-drop',payload:{paths:[path.resolve('.test-artifacts/subtitle-test.mp4')],position:{x:0,y:0}}});
 await p.waitForFunction(async()=>{try{return await window.__TAURI_INTERNALS__.invoke('plugin:libmpv|get_property',{name:'duration',format:'double',windowLabel:'main'})>8;}catch{return false;}});
 await invoke('plugin:event|emit',{event:'analysis-partial',payload:[{startMs:500,endMs:1000,text:'One'},{startMs:4000,endMs:5000,text:'Two'}]});
 await p.waitForFunction(()=>document.querySelectorAll('textarea').length===2);
 await invoke('plugin:libmpv|command',{name:'seek',args:[2.375,'absolute','exact'],windowLabel:'main'});await p.waitForTimeout(150);
 await p.getByTitle('Add subtitle',{exact:true}).click();
 const rows=p.locator('[data-cue-id]');await p.waitForFunction(()=>document.querySelectorAll('textarea').length===3);
 const values=()=>p.locator('textarea').evaluateAll(es=>es.map(e=>e.value));assert.deepEqual(await values(),['One','','Two']);
 const time=await rows.nth(1).getByLabel('IN',{exact:true}).inputValue();
 const delay=await p.evaluate(()=>JSON.parse(localStorage.getItem('subscreen:subtitle-style')||'{}').delay||0);const ms=2375-delay*1000;
 assert.equal(time,`00:00:${String(Math.floor(ms/1000)).padStart(2,'0')},${String(ms%1000).padStart(3,'0')}`);
 await p.keyboard.press('Control+z');assert.deepEqual(await values(),['One','Two']);
 await p.keyboard.press('Control+y');assert.deepEqual(await values(),['One','','Two']);
 await rows.nth(1).locator('textarea').fill('Inserted');
 await rows.nth(1).getByTitle('Move up (swap timings)',{exact:true}).click();assert.deepEqual(await values(),['Inserted','One','Two']);
 assert.equal(await rows.first().getByLabel('IN',{exact:true}).inputValue(),'00:00:00,500');
 assert.equal(await rows.first().getByLabel('OUT',{exact:true}).inputValue(),'00:00:01,000');
 assert.equal(await rows.nth(1).getByLabel('IN',{exact:true}).inputValue(),time);
 await p.keyboard.press('Control+z');assert.deepEqual(await values(),['One','Inserted','Two']);
 await p.keyboard.press('Control+y');assert.deepEqual(await values(),['Inserted','One','Two']);
 await rows.first().getByTitle('Delete cue',{exact:true}).click();assert.deepEqual(await values(),['One','Two']);
 await p.keyboard.press('Control+z');assert.deepEqual(await values(),['Inserted','One','Two']);
 await p.keyboard.press('Control+y');assert.deepEqual(await values(),['One','Two']);
 await p.getByTitle('Undo (Ctrl+Z)',{exact:true}).click();assert.deepEqual(await values(),['Inserted','One','Two']);
 assert.equal(await p.locator('img[src="/app-icon.png"]').count(),1);
 assert.equal(await p.locator('a[href="https://github.com/neura-neura/subscreen"]').count(),1);
 await p.screenshot({path:'.test-artifacts/editor-030.png'});
 console.log('Add at exact playhead, empty text, cue ordering, times swapped, Ctrl+Z/Ctrl+Y, undo button, logo: PASS');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
