const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const root='C:\\Users\\neura\\repos\\subscreen\\.test-artifacts\\';
(async()=>{
 const browser=await chromium.connectOverCDP('http://127.0.0.1:9224');
 const page=browser.contexts()[0].pages().find(p=>p.url().includes('tauri.localhost'));
 if(!page)throw Error('App webview not found');
 page.on('pageerror',e=>console.error('PAGE ERROR',e));
 await page.evaluate(path=>window.__TAURI_INTERNALS__.invoke('plugin:event|emit',{event:'tauri://drag-drop',payload:{paths:[path],position:{x:0,y:0}}}),root+'subtitle-test.mp4');
 await page.getByRole('button',{name:'Select area',exact:true}).waitFor();
 await page.waitForFunction(()=>!document.querySelector('button[aria-label="Play"]')?.disabled);
 assert.equal(await page.locator('html').evaluate(el=>el.classList.contains('mpv-active')),true);
 const backgrounds=await page.locator('.player-card, .video-stage, main').evaluateAll(els=>els.map(el=>getComputedStyle(el).backgroundColor));
 assert(backgrounds.every(bg=>bg==='rgba(0, 0, 0, 0)'),JSON.stringify(backgrounds));
 await page.getByRole('button',{name:'Select area',exact:true}).dispatchEvent('click');
 const r=await page.locator('.video-stage').boundingBox();
 await page.mouse.move(r.x+5,r.y+r.height*.78);await page.mouse.down();await page.mouse.move(r.x+r.width-5,r.y+r.height-5,{steps:8});await page.mouse.up();
 await page.evaluate(async()=>{window.progress=[];await window.__TAURI_INTERNALS__.invoke('plugin:event|listen',{event:'analysis-progress',target:{kind:'Any'},handler:window.__TAURI_INTERNALS__.transformCallback(event=>window.progress.push(event.payload.percent))});});
 await page.getByRole('button',{name:'Analyze subtitles',exact:true}).dispatchEvent('click');
 await page.waitForFunction(()=>window.progress.includes(100),{},{timeout:120000});
 const cues=await page.locator('textarea').evaluateAll(els=>els.map(el=>el.value));
 assert.equal(cues.length,3,JSON.stringify(cues));
 assert.equal(cues[0],'你好，世界！今天是美好的一天。');
 assert.equal(cues[1],'Hello world! This is a subtitle.');
 assert.equal(cues[2],'¡Hola! ¿Cómo estás? Mañana será mejor.');
 const progress=await page.evaluate(()=>window.progress);assert(progress.some(n=>n>0&&n<100));
 console.log('OCR + mpv + progress: PASS',cues,progress.length);
 await page.locator('summary').click();
 const originalDelay=await page.getByLabel('Delay (seconds)').inputValue();
 await page.getByLabel('Delay (seconds)').fill('0.5');
 await page.getByLabel('Delay (seconds)').press('Tab');
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('subscreen:subtitle-style')).delay),.5);
 await page.evaluate(async root=>{
  const style={font:'Segoe UI',size:24,color:'#ffffff',outline:2,bottom:8,background:false};
  await window.__TAURI_INTERNALS__.invoke('burn_subtitles',{videoPath:root+'subtitle-test.mp4',outputPath:root+'burned.mp4',srtContent:'1\n00:00:00,500 --> 00:00:02,000\nExport preview test\n',style});
 },root);
 console.log('NVENC export: PASS');
 await page.getByLabel('Delay (seconds)').fill(originalDelay);
 await page.getByLabel('Delay (seconds)').press('Tab');
 await browser.close();
})().catch(e=>{console.error(e);process.exitCode=1;});
